# Generated by Django 4.2.14 on 2024-07-16 18:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_description_en_about_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
