# Generated by Django 4.2.14 on 2024-07-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.country'),
        ),
    ]
