# Generated by Django 4.2.14 on 2024-07-22 11:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_parent_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='name_ru',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='name_uz',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
