# Generated by Django 4.2.14 on 2024-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_content_en_article_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
