# Generated by Django 4.2.14 on 2024-07-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Confirmed'), (2, 'Canceled')], default=0)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('people', models.PositiveIntegerField(default=1)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', related_query_name='booking', to='tour.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
