# Generated by Django 4.2.14 on 2024-07-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_bookingtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtour',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Chegirma'),
        ),
    ]
