# Generated by Django 4.2.14 on 2024-07-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_bookingtour_date_tour_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='discount',
        ),
    ]
