# Generated by Django 4.2.14 on 2024-07-22 11:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_remove_tour_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayohat davomiyligi'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayohat davomiyligi'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayohat davomiyligi'),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_uz',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='name_ru',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='name_uz',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
