# Generated by Django 4.2.14 on 2024-07-23 18:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_country_options_alter_country_flag_and_more'),
        ('tour', '0006_tour_description_en_tour_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingtour',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Sayohat', 'verbose_name_plural': 'Sayohatlar'},
        ),
        migrations.AlterModelOptions(
            name='tourgallery',
            options={'verbose_name': 'Galereya', 'verbose_name_plural': 'Sayohat Galereyalari'},
        ),
        migrations.AlterModelOptions(
            name='tourplan',
            options={'verbose_name': 'Sayohat reja', 'verbose_name_plural': 'Sayohat rejalar'},
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Ism Familiya'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='people',
            field=models.PositiveIntegerField(default=1, verbose_name='Odamlar soni'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Confirmed'), (2, 'Canceled')], default=0, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', related_query_name='booking', to='tour.tour', verbose_name='Sayohat'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country', verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name_uz',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tourgallery',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm hajmi 1,200x1,700 px bo'lishi kerak. Havola: https://pexels.com/", null=True, upload_to='galleries/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='tourgallery',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', related_query_name='gallery', to='tour.tour', verbose_name='Sayohat'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='name_en',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='name_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='name_uz',
            field=models.CharField(max_length=225, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', related_query_name='plan', to='tour.tour', verbose_name='Sayohat'),
        ),
    ]
