# Generated by Django 4.2.14 on 2024-07-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_bookingtour_options_alter_tour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgallery',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm hajmi 1200x1700 px bo'lishi kerak. Havola: https://pexels.com/", null=True, upload_to='galleries/', verbose_name='Rasm'),
        ),
    ]
